### ISSUE TITLE
#58 네비바 backbutton title 노출 이슈

### ISSUE THREAD

**Issue by ebPark9511** [Ludus-soyeon/soyeon-ios#75]
## 💡 네비바 backbutton title 노출 이슈

<img width="596" alt="스크린샷 2021-02-28 오전 1 03 03" src="https://user-images.githubusercontent.com/33455020/109392683-da3a3080-7960-11eb-8419-35d456b6e43c.png">

> @junyng 님이 #57 에서 작업해주신 네비바의 back button title이 노출되고 있습니다.

- [ ]   title이 노출되지 않도록 수정 필요합니다.

작업 부탁드립니다!

**Comment by junyng** [comment]
현재 구현되어 있는 `setNavigationTitle` 메서드는 
navigation title에 빈 값을 넣어주고 custom view로 `label`을 넣어주고 있어서
모든 뷰 컨트롤러에 적용이 필요해요
`setNavigationTitle` 메서드가 적용되지 않은 뷰 컨트롤러에 대해 고민을 해볼게요.!
